#:kivy 1.0.9
#:import Gradient kivy_gradient.Gradient
#:import Color kivy.graphics.Color
#:import Rectangle kivy.graphics.Rectangle

# Individual square on the board
<Square@Button>:
    top: root.top
    width: root.width

# 3x3 grid of squares
<Board@GridLayout>:
    top: root.top
    width: root.width
    cols: 3
    rows: 3
    padding: 2
    orientation: 'lr-tb'

# Main frame of the app
<FrameScreen>:
    carousel: screen_selection
    orientation: 'vertical'
    md_bg_color: self.theme_cls.bg_dark

    MDAnchorLayout:
        anchor_x: 'center'
        anchor_y: 'top'

        # Header for app
        MDLabel:
            text: "Sudoku"
            font_size: 70
            halign: "center" #center_x: root.width/2
            #top: root.top-10
            height: 70
            theme_text_color: "Primary"
            #spacing: 30

    RelativeLayout:
        Carousel:
            id: screen_selection
            direction: "right"
            scroll_timeout: 0

            size_hint_x: None
            width: root.width
            center_x: root.width/2

            size_hint_y: None
            height: root.top-100
            center_y: (root.height-100)*1/2

    # Bottom copyright text
    Label:
        id: copyright
        text: "© 2025 Regina Reynolds"
        font_size: 20
        center_x: root.width/2
        top: root.top-10
        height: 20


# Difficulty selection screen
<DifficultyScreen>:
    options: difficulty_selection

    # Header for difficulty selection
    Label:
        text: "Select a difficulty"
        font_size: 50
        color: 1, 1, 1, 1

        size_hint_x: None
        width: root.width*2/3
        center_x: root.width/2

        size_hint_y: None
        height: root.top/4
        center_y: (3*root.height+60)/4

    # Grid of difficulty buttons
    GridLayout:
        id: difficulty_selection
        cols: 3
        spacing: 20
        padding: 20

        size_hint_x: None
        width: root.width*2/3
        center_x: root.width/2

        size_hint_y: None
        height: (root.top-85)/2
        center_y: (root.height+20)/2

        Button:
            text: "Easy"
            font_size: self.height/4
    
        Button:
            text: "Medium"
            font_size: self.height/4

        Button:
            text: "Hard"
            font_size: self.height/4

<LoadingScreen>:
    progress: scraping_progress

    Label:
        id: loading_text
        text: "Scraping puzzle..."
        font_size: 50

        size_hint_x: None
        width: root.width*2/3
        center_x: root.width/2

        size_hint_y: None
        height: root.top/4
        center_y: (3*root.height+60)/4
        

    ProgressBar:
        id: scraping_progress
        size_hint_x: None
        width: root.width*2/3
        center_x: root.width/2
        center_y: (root.height+20)/2
        max: 81

<PuzzleScreen>:
    board: boxes

    Board:
        id: boxes
        top: root.top
        width: root.width
        row_default_height: (root.top-10)/3
        padding: 5

        Board:
        Board:
        Board:
        Board:
        Board:
        Board:
        Board:
        Board:
        Board: