#:kivy 1.0.9
#:import Gradient kivy_gradient.Gradient
#:import Color kivy.graphics.Color
#:import Rectangle kivy.graphics.Rectangle
#:import MDRaisedButton kivymd.uix.button.MDRaisedButton
#:import MDLabel kivymd.uix.label.MDLabel
#:import MDProgressBar kivymd.uix.progressbar.MDProgressBar
#:import MDCard kivymd.uix.card.MDCard
#:import MDIconButton kivymd.uix.button.MDIconButton

# Difficulty card widget
<DifficultyCard@MDCard>:
    difficulty_text: "Placeholder"
    difficulty_icon: "Placeholder"
    difficulty_description: "Placeholder"
    difficulty_color: "blue"

    orientation: 'vertical'
    adaptive_height: True
    padding: 12
    spacing: 12
    size_hint: None, None
    size: "200dp", "200dp"

    style: "elevated"
    padding: "12dp"
    spacing: "12dp"

    ripple_behavior: True
    on_release: root.callback(self)
    orientation: "vertical"
    md_bg_color: root.difficulty_color
    elevation_level: 5

    # Card icon
    MDIconButton:
        id: difficulty_icon
        icon: root.difficulty_icon # "grid"
        pos_hint: {"center_x": .5}
        theme_icon_color: "Custom"
        icon_color: 1, 1, 1, 1
        icon_size: "48dp"

    # Difficulty label
    MDLabel:
        id: difficulty_text
        text: root.difficulty_text
        theme_text_color: "Custom"
        text_color: 1, 1, 1, 1
        font_style: "H5"
        bold: True
        halign: "center"
        adaptive_height: True

    # Difficulty description
    MDLabel:
        id: difficulty_description
        text: root.difficulty_description
        theme_text_color: "Custom"
        text_color: .9, .9, .9, 1
        halign: "center"
        adaptive_height: True

        # Start game button
        MDRaisedButton:
            text: "Start Game"
            pos_hint: {"center_x": .5}
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1
            md_bg_color: root.difficulty_color

# Individual square on the board
<Square@Button>:
    top: root.top
    width: root.width

# 3x3 grid of squares
<Board@GridLayout>:
    top: root.top
    width: root.width
    cols: 3
    rows: 3
    padding: 2
    orientation: 'lr-tb'

# Main frame of the app
<FrameScreen>:
    carousel: screen_selection
    orientation: 'vertical'
    md_bg_color: self.theme_cls.bg_dark

    MDAnchorLayout:
        anchor_x: 'center'
        anchor_y: 'top'

        # Header for app
        MDLabel:
            text: "Sudoku"
            font_size: 70
            halign: "center"
            size_hint_y: None
            height: 70
            theme_text_color: "Primary"

    RelativeLayout:
        Carousel:
            id: screen_selection
            direction: "right"
            scroll_timeout: 0

            size_hint_x: None
            width: root.width
            center_x: root.width/2

            size_hint_y: None
            height: root.top-100
            center_y: (root.height-100)*1/2

    MDAnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'

        # Bottom copyright text
        MDLabel:
            id: copyright
            text: "© 2025 Regina Reynolds"
            font_size: 20
            halign: "center"
            size_hint_y: None
            height: 20
            theme_text_color: "Secondary"

# Difficulty selection screen
<DifficultyScreen>:
    options: difficulty_selection

    # Header for difficulty selection
    Label:
        text: "Select a difficulty"
        font_size: 50
        color: 1, 1, 1, 1

        size_hint_x: None
        width: root.width*2/3
        center_x: root.width/2

        size_hint_y: None
        height: root.top/4
        center_y: (3*root.height+60)/4

    # Grid of difficulty buttons
    GridLayout:
        id: difficulty_selection
        cols: 3
        spacing: 20
        padding: 20

        size_hint_x: None
        width: root.width*2/3
        center_x: root.width/2

        size_hint_y: None
        height: (root.top-85)/2
        center_y: (root.height+20)/2

        Button:
            text: "Easy"
            font_size: self.height/4
    
        Button:
            text: "Medium"
            font_size: self.height/4

        Button:
            text: "Hard"
            font_size: self.height/4

<LoadingScreen>:
    progress: scraping_progress

    Label:
        id: loading_text
        text: "Scraping puzzle..."
        font_size: 50

        size_hint_x: None
        width: root.width*2/3
        center_x: root.width/2

        size_hint_y: None
        height: root.top/4
        center_y: (3*root.height+60)/4
        

    ProgressBar:
        id: scraping_progress
        size_hint_x: None
        width: root.width*2/3
        center_x: root.width/2
        center_y: (root.height+20)/2
        max: 81

<PuzzleScreen>:
    board: boxes

    Board:
        id: boxes
        top: root.top
        width: root.width
        row_default_height: (root.top-10)/3
        padding: 5

        Board:
        Board:
        Board:
        Board:
        Board:
        Board:
        Board:
        Board:
        Board: