#:kivy 1.0.9

<FrameScreen>:
    screens: screen_selection
    Label:
        text: "Sudoku"
        font_size: 70
        center_x: root.width/2
        top: root.top-10
        height: 70

    RelativeLayout:
        Carousel:
            id: screen_selection
            direction: "right"
            scroll_timeout: 0

            size_hint_x: None
            width: root.width
            center_x: root.width/2

            size_hint_y: None
            height: root.top-100
            center_y: (root.height-100)*1/2

<DifficultyScreen>:
    options: difficulty_selection

    Label:
        text: "Select a difficulty"
        font_size: 50

        size_hint_x: None
        width: root.width*2/3            
        center_x: root.width/2
        
        size_hint_y: None
        height: root.top/4
        center_y: (3*root.height+60)/4

    GridLayout:
        id: difficulty_selection
        cols: 3
        padding: 2
        orientation: 'lr-tb'
        
        size_hint_x: None
        width: root.width*2/3            
        center_x: root.width/2
        
        size_hint_y: None
        height: (root.top-85)/4
        center_y: (root.height+20)/2

        Button:
            text: "Easy"
    
        Button:
            text: "Medium"

        Button:
            text: "Hard"            